POST http://localhost:5035/connect
Content-Type: application/json

{
  "IpAddress": "127.0.0.1",
  "UserName": "brito",
  "Password": "password",
  "Port": "21"
}


POST http://localhost:5035/connect
Content-Type: application/json

{
  "IpAddress": "192.168.43.151",
  "UserName": "android",
  "Password": "android",
  "Port": "2020"
}



